site_name: wiki.simon.tf
site_url: https://wiki.simon.tf
repo_name: 'barnumbirr/wiki'
repo_url: 'https://github.com/barnumbirr/wiki'
copyright: |
  Copyright &copy; 2021-2024 Martin Simon

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: fontawesome/solid/book
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  analytics:
    provider: plausible
    domain: wiki.simon.tf
    script_url: https://plausible.io/js/plausible.outbound-links.js
